all: happy.c recursion.c bunny.c waiter.c www.c
	gcc -g happy.c -o happy
	gcc -g recursion.c -o recursion
	gcc -g bunny.c -o bunny
	gcc -g waiter.c -o waiter
	gcc -g www.c -o www

clean:
	rm happy
	rm recursion
	rm bunny
	rm waiter
	rm www


